### PR TITLE
revert back to right commit in spirv-cross

### PR DESCRIPTION
**Pull request by rafaga**
reverting commit to the right one rcomended by KhronosGroup

### CODE REVIEW

**Comment by yurikoles** [comment]
@rafaga it's nice to have CI ;)

**Comment by yurikoles** [comment]
@rafaga do you have some conversation with upstream except our ticket that I had filled?

**Comment by rafaga** [comment]
@yurikoles It is good to have CI, and I don't what exactly did you mean with conversation with upstream, can you explain further ?

**Comment by yurikoles** [comment]
I mean Khronos Group's MoltenVK project. Is someone contacted you except public conversation in ticket?

Do you know that Valve (rumors say that they bought MoltrnVK and donated it to Khronos) hired main DXVK developer/author and a lot of Mesa3D contributors.

**Comment by rafaga** [comment]
Nope, nobody has made contact. It is just what is on the ticket. 

> Do you know that Valve (rumors say that they bought MoltrnVK and donated it to Khronos) hired main DXVK developer/author and a lot of Mesa3D contributors.

I didn't know it, but it makes a lot of sense, Valve has invested a LOT on Vulkan it will be good having a company like Valve pushing resources into projects like this.

**Pull request closed without merging**
